name: reuse
on:
    workflow_call:
      outputs:
        outputpass:
          value: ${{ jobs.job1.outputs.output1 }} 
      inputs:
        firstinput:
            type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.outputid.outputs.name }}
    steps:
    - name: demo
      id: outputid
      run: echo "name=asif" >> $GITHUB_OUTPUT
          
        